version: '3.8'

services:
  web:
    build: .
    container_name: cv_flask_web
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./etc/nginx/servers/default.conf
    depends_on:
      - web
    restart: always